### ISSUE TITLE
Integrate grocer functionality from UpDayton brochure

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/grocer#3]
![finalmap](https://f.cloud.github.com/assets/1282711/2516448/1c10c63e-b44e-11e3-8e40-f3c860fb878c.jpg)

**Comment by AMGlett** [comment]
This is how UpDayton used the data, I figured since the last meeting had everyone working with JSON conversion and stuff, you might want to see this to make sense of the data. I know that it makes more sense when you see the data used in context, and I expect it to be more useful to know why it contains what it does. They concentrated on a 4 mile radius from the downtown and then included CSAs (Community Supported Agriculture) as well. The data goes into details of what the grocery stores do and don't typically carry, what bus routes are nearby, and their operating hours and contact information. So it might be useful to keep some of that data so that the various functions of the printed map can be integrated with the application based one.

**Comment by AMGlett** [comment]
I checked the Geo.JSON file against the pamphlet, it seems to coincide. No data was lost. If you guys want to keep this file around for reference, that's fine, but I think the issues that I thought having it around for are resolved.

**Comment by raudabaugh** [comment]
Thanks for looking into this. I'll go ahead and close the issue.
